### ISSUE TITLE
Add version to the filename of libhrpio.so

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#1]
Adding version number into the name of `libhrpio.so` and linking to it might ease the pain of detecting the version the file was built on.

If this makes sense, how should it be named like? `libhrpio.so.315.1.7` (based on `hrpsys`)? `libhrpio.so.3.1.5` (`OpenHRP3`)?

@k-okada @emijah

**Comment by emijah** [comment]
It is based on hrpsys-base, so I think the version number should match that.

**Comment by 130s** [comment]
Will do `libhrpio.so.315.1.7` this time then. Thank you!
