### ISSUE TITLE
HIRONX .setTargetPose doesn't show anything on its terminal upon IK failure

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#103]
The method returns without showing anything (other than printing the input value) about the failure.

On simulation, only on the terminal where `hironx_starup.launch` runs (where `hrpsys.launch` runs), I see that IK solution was not found.

```
14.119767661, 2869.800000039]: [HrpsysSeqStateROSBridge0] @onExecutece 0 is working at 196[Hz]
[rtmlaunch] Wait for  /localhost:15005/CollisionDetector0.rtc   20 /30
[ INFO] [1401502115.238850209, 2870.840000039]: [HrpsysSeqStateROSBridge0] @onExecutece 0 is working at 197[Hz]
IK Fail, iter = 50
  err : 1.5624e-07 ( 0.000193918 2.54446e-05 -0.000343494) < 1e-08
      : 1.21612e-09 ( 2.66772e-05 -1.50533e-05 1.66688e-05) < 1e-06
[setTargetPose] IK failed
```

I think user of `HIRONX` doesn't (have to) always pay attention to this terminal above. Moreover this output may not be visible when running on real robot.

I don't know which package is the best place to discuss this so started here.

**Comment by k-okada** [comment]
Good point this should be fixed in hrpsys_cinfig.py at rtmros_common
First step is just simply say something wrong if it returns failure
If you would like to return the error message, we need to create another idl interface to do that

**Comment by 130s** [comment]
Thank you, I created a [tentative patch](https://github.com/fkanehiro/hrpsys-base/pull/233) against `hrpsys-base`. At least with that patch users can know that errors are happening, however it's not yet sufficiently pleasant for those who want to look at the actual IK error values.
