### ISSUE TITLE
How to control hands via ROS

### ISSUE THREAD

**Issue by hyaguchijsk** [start-jsk/rtmros_hironx#111]
Hi all,

I'm trying to control hands.
I found some methods in `hironx_client.py` and checked with hiro014,
but I could not find any methods via ROS.
How can I control hands from my own ros node?

regards,

**Comment by k-okada** [comment]
please check if https://github.com/fkanehiro/hrpsys-base/tree/master/rtc/ServoController is running and corresponding ROS-Bridge is also compiled and running. if so,https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L173 code will take care of controlling hands.

**Comment by hyaguchijsk** [comment]
`ServoController` is running as `sc.rtc` and I can control hands via `hironx_client.py`.
When using this, my own code should import `hironx.py` directly,
like,

```
execfile(
  roslib.packages.get_pkg_dir('hironx_ros_bridge') + '/scripts/hironx.py',
  globals())
```

and args `-- --robot RobotHardware0 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl --host hiro014 --port 15005` should be set.
I think this is not smart way, and also this can runs only with Python nodes.

So I'd like to control hands via rosservice, but I could not find it.

**Comment by k-okada** [comment]
Please check if ServoControllerROSBridge is running. if not, please test  with https://github.com/start-jsk/rtmros_hironx/pull/112, this code also requires some information on conf file(https://github.com/fkanehiro/hrpsys-base/blob/master/rtc/ServoController/ServoController.cpp#L81), please check hiro machine with
`grep -ri servo.devname ~/" command. I think we have previous setup somewhere.

also `import hironx.py dir` should not be like that, you can import them as https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/test_hironx.py#L13, if you still unclear please open different PR

**Comment by hyaguchijsk** [comment]
OK, hands can be controlled via ROS using this. thanks.

`servo.devname` is defined at
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/robot/Robot.conf.in#L9

I've checked with hiro014, and this worked well with pretty diff.

```
diff --git a/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch b/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
index 9ef94b3..e55b845 100644
--- a/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
+++ b/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
@@ -62,7 +62,7 @@
         args="$(arg MODEL_FILE) $(arg SIMULATOR_NAME) HrpsysSeqStateROSBridge0 $(arg nameserver) $(arg omniorb_args)" output="$(arg OUTPUT)"/>
   <!-- BEGIN:openrtm connection -->
   <env name="SIMULATOR_NAME" value="$(arg SIMULATOR_NAME)" />
-  <node name="rtmlaunch_hrpsys_ros_bridge" pkg="openrtm_tools" type="rtmlaunch.py" args="$(find hrpsys_ros_bridge)/launch/hrpsys_ros_bridge.launch USE_COMMON=$(arg USE_COMMON) USE_WALKING=$(arg USE_WALKING) USE_COLLISIONCHECK=$(arg USE_COLLISIONCHECK) USE_IMPEDANCECONTROLLER=$(arg USE_IMPEDANCECONTROLLER) USE_SOFTERRORLIMIT=$(arg USE_SOFTERRORLIMIT) USE_IMAGESENSOR=$(arg USE_IMAGESENSOR) USE_ROBOTHARDWARE=$(arg USE_ROBOTHARDWARE) USE_TORQUECONTROLLER=$(arg USE_TORQUECONTROLLER) USE_TORQUEFILTER=$(arg USE_TORQUEFILTER)" output="$(arg OUTPUT)"/>
+  <node name="rtmlaunch_hrpsys_ros_bridge" pkg="openrtm_tools" type="rtmlaunch.py" args="$(find hrpsys_ros_bridge)/launch/hrpsys_ros_bridge.launch USE_COMMON=$(arg USE_COMMON) USE_WALKING=$(arg USE_WALKING) USE_COLLISIONCHECK=$(arg USE_COLLISIONCHECK) USE_IMPEDANCECONTROLLER=$(arg USE_IMPEDANCECONTROLLER) USE_SOFTERRORLIMIT=$(arg USE_SOFTERRORLIMIT) USE_IMAGESENSOR=$(arg USE_IMAGESENSOR) USE_ROBOTHARDWARE=$(arg USE_ROBOTHARDWARE) USE_GRASPCONTROLLER=$(arg USE_GRASPCONTROLLER) USE_SERVOCONTROLLER=$(arg USE_SERVOCONTROLLER) USE_TORQUECONTROLLER=$(arg USE_TORQUECONTROLLER) USE_TORQUEFILTER=$(arg USE_TORQUEFILTER)" output="$(arg OUTPUT)"/>


   <!-- All Robots -->
@@ -173,7 +173,7 @@
   <group if="$(arg USE_SERVOCONTROLLER)" >
     <node pkg="hrpsys_ros_bridge" name="ServoControllerServiceROSBridge" type="ServoControllerServiceROSBridgeComp"
           output="screen" args ="$(arg openrtm_args)" />
-    <rtconnect from="ServoControllerServiceROSBridge.rtc:ServoControllerService" to="gc.rtc:ServoControllerService"  subscription_type="new"/>
+    <rtconnect from="ServoControllerServiceROSBridge.rtc:ServoControllerService" to="sc.rtc:ServoControllerService"  subscription_type="new"/>
     <rtactivate component="ServoControllerServiceROSBridge.rtc" />
   </group>
```

**Comment by k-okada** [comment]
could you send pull request for you change ? and also it would be very helpful if you write new tutorial such as Using HiroNX Grippers (servo grippers) on http://wiki.ros.org/rtmros_nextage/Tutorials,  I'm pretty sure that @130s will correct English

**Comment by hyaguchijsk** [comment]
I created PReq to @k-okada repo, please check.
