### ISSUE TITLE
Add "start up guide" (a page-long or similar)

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#120]
Examples available online:
- [PR2](http://wiki.ros.org/pr2_robot/Tutorials/Starting%20up%20the%20PR2)
- [Baxter Reseach](http://sdk.rethinkrobotics.com/wiki/Getting_Started)

**Comment by 130s** [comment]
Started [here](http://wiki.ros.org/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users)

**Comment by k-okada** [comment]
good may I help?
- Power the computers -> this should be contributed from hardware manufactular
- Connect to the robot -> http://wiki.ros.org/rtmros_nextage/Tutorials/Operating%20Hiro%2C%20NEXTAGE%20OPEN%20from%20Client%20Pograms#With_a_real_robot
- Do the simplest move ->  http://wiki.ros.org/rtmros_nextage/Tutorials/Operating%20Hiro%2C%20NEXTAGE%20OPEN%20from%20Client%20Pograms#Operate_robot_via_hrpsys_in_Python
- Run sample codes -> depends on https://github.com/start-jsk/rtmros_hironx/issues/128 ?? need to develop software?

**Comment by k-okada** [comment]
http://wiki.ros.org/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users

```
$ ipython -i `rospack find hironx_ros_bridge`/test/acceptancetest_hironx.py -- --robot RobotHardware0 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl --host %HOSTNAME% --port 15005
```

I think location of model file is differnt

**Comment by k-okada** [comment]
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/acceptancetest_hironx.py#L216 tells we do not need '--robot RobotHardware0' if we use "--host" option, and "--port" is also not required, default  value is ok (https://github.com/fkanehiro/hrpsys-base/blob/master/python/rtm.py#L267),

**Comment by 130s** [comment]
> ```
> $ ipython -i `rospack find hironx_ros_bridge`/test/acceptancetest_hironx.py -- --robot RobotHardware0 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl --host %HOSTNAME% --port 15005
> ```
> 
> I think location of model file is differnt

I thought we agreed on sticking to `/opt/jsk/etc/HIRONX` for now to focus on the current installation work. https://github.com/start-jsk/rtmros_hironx/commit/f3e04bcd438b25d75bdbf0b55ce165e797e08105#diff-aec30a089e4808217be1e325e9920063R42

**Comment by 130s** [comment]
> https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/acceptancetest_hironx.py#L216 tells we do not need '--robot RobotHardware0' if we use "--host" option, and "--port" is also not required, default value is ok (https://github.com/fkanehiro/hrpsys-base/blob/master/python/rtm.py#L267), 

Thank you, [applied](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users?action=diff&rev2=17&rev1=16).

**Comment by k-okada** [comment]
> I thought we agreed on sticking to /opt/jsk/etc/HIRONX for now to focus on the current installation work. f3e04bc

Oh, I missed that. Ok

**Comment by 130s** [comment]
[Done](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users?action=diff&rev2=37&rev1=34).
