### ISSUE TITLE
robot-system-check-base looks for strange file?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#122]
```
 ** /usr/pkg/lib/perl5/5.10.0/Getopt/Std.pm          is not found on database
 ** /usr/pkg/lib/perl5/5.10.0/Getopt/Long.pm         is not found on database
 ** /usr/pkg/lib/perl5/5.10.0/Get/opt/Std.pm         is not found
 ** /usr/pkg/lib/perl5/5.10.0/Get/opt/Long.pm        is not found
```

About [md5sum_usr_pkg_lib.py](https://github.com/start-jsk/rtmros_hironx/blob/671525c6d98a67d0ffe5167a744840ff2aa096fc/hironx_ros_bridge/robot/check/md5sum_usr_pkg_lib.py),
- Under `/usr/pkg/lib/perl5/5.10.0/Getopt/`,  `Std.pm` and `Long.pm` are contained. So why `not found on database`?
- it doesn't contain the folder `/usr/pkg/lib/perl5/5.10.0/Get/opt`. Other md5sum py files either.

**Comment by k-okada** [comment]
please confirm database files that is used for create your db file

**Comment by 130s** [comment]
Closing since https://github.com/tork-a/delivery/issues/27 (private repo) is now good.
