### ISSUE TITLE
Add acceptance test via ROS api

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#128]
Implements the same tasks that [this `hrpsys` version does](https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/acceptancetest_hironx.py).

**Comment by k-okada** [comment]
if you need help on writing this code, please let me know.

**Comment by k-okada** [comment]
I think we need, hrpsys version, ROS/Python version, ROS/C++ version, MoveIt version.

**Comment by 130s** [comment]
Thank you for the offer! For the user I'm working with right now, at least we need hrpsys ([added](https://github.com/start-jsk/rtmros_hironx/commit/76a8f3868367f28fccbf44f367ec41007ceeec59#diff-e63ac1f487a7784813b73e698d8bebde)) and ROS-python version until July 18th. 

Just spreading my thoughts for ROS samples; I thought for using `JointTrajectoryControl` in ROS we need to add controller for it. So it's much simpler to just write `MoveIt!` sample (no `JointTrajectoryControl` sample) since MoveIt! config is already packaged (as `hironx_moveit_config`). But I'm afraid with MoveIt! we might not be able to write tasks with specific joint poses, and real-time control by interruption either.

**Comment by k-okada** [comment]
rtmros_common already provide pr2_controllers_msgs::JointTrajectoryAction / control_msgs::FollowJointTrajectoryAction. so you do not need to add controller.
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/HrpsysJointTrajectoryBridge.cpp#L223.

As for moveit, I think you're right

**Comment by 130s** [comment]
Done in https://github.com/start-jsk/rtmros_hironx/pull/171

> rtmros_common already provide pr2_controllers_msgs::JointTrajectoryAction / control_msgs::FollowJointTrajectoryAction. 

That was helpful for me to know that the ROS controllers are already running. In the PReq above, however, because I wasn't sure how to call the running action clients from those `Action`s from python, I ended up generating new `SimpleActionClient`s for each joint group. Hope it's not too redundant, but if it is we can replace it.

**Comment by k-okada** [comment]
On Sun, Jul 20, 2014 at 4:27 PM, Isaac I.Y. Saito notifications@github.com 
wrote:

> because I wasn't sure how to call the running action clients from those 
> Actions from python, I ended up generating new SimpleActionClients for 
> each joint group. 

I think this is usual way to write action client, 
if you can search all ros service that reads 
control_msgs::FollowJointTrajectoryActionGoal, then you can create action 
client on demand as 
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L102
