### ISSUE TITLE
ipythonを使う時の引数がおかしい？

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#14]
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/scripts/hironx.py#L46
で，
`# ./ipython -i hironx.py --host hiro014`
と書いてあるけど，
`# ./ipython -i hironx.py -- --host hiro014`
では？

**Comment by 130s** [comment]
Fixed via b10936e
