### ISSUE TITLE
Hironx? Nextage Open? Decide policy folder name policy

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#140]
Continued from https://github.com/k-okada/rtmros_hironx/commit/8260c66b673d75be157c810b69be675b4fd62d75#commitcomment-6905991, and https://github.com/start-jsk/rtmros_hironx/commit/34437dd16be1b9e884c140979caffc9ad83e0cb5#commitcomment-6905457

I guess there are two types of folder name conventions that involve robot's name (`Hiro` or `Nextage Open`) we may want to follow:
- Model file: Since even a slight difference between two sibling robots is significant, we still  want to identify each.
- Other: If the folder isn't intimately related to either robot specifically, we can consolidate to either Hiro or NXO. And because we've been already leaning toward to NXO ([example](https://github.com/start-jsk/rtmros_hironx/issues?direction=desc&sort=updated&state=open)), I suggest to NXO consistently from now on.

If this is ok we need to keep finding what needs updated.

**Comment by 130s** [comment]
A question; do we want to separate install-related script ([like this](https://github.com/start-jsk/rtmros_hironx/pull/137)) for Hiro and NXO?

**Comment by k-okada** [comment]
if you can manage two different script separately, please do so, but I suggest concentrate on NXO at this time, to avoid confusion and/or worry about  HIRO.

**Comment by 130s** [comment]
In #297 this concern is handled; installer script installs models for both Hiro and NX.
