### ISSUE TITLE
reference vs current

### ISSUE THREAD

**Issue by kindsenior** [start-jsk/rtmros_hironx#15]
As we confused at https://code.google.com/p/hrpsys-base/issues/detail?id=182, 
getJointAngles() returns current commanded angles, and hcf.rh_svc.getStatus().angle returns current actual robot's angles.

https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L597
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L270

getReferencePose() and getCurrentPose() are also same situation. one is current pose and another one is commanded(reference) pose.

https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L547
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L607

**Comment by 130s** [comment]
Good point in timely fashion. I'm updating api docs right now and will
reflect your comments.

**Comment by 130s** [comment]
@kindsenior I've committed [some document](https://github.com/start-jsk/rtmros_hironx/commit/b3782ad7f7a0ca0478d6062f618921fdeff51dbb). Please give feedback and reopen if anything.
