### ISSUE TITLE
robot-compile-setup.sh puts NXO model files into wrong directory inside the robot

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#160]
[This line](https://github.com/start-jsk/rtmros_hironx/blob/f3e04bcd438b25d75bdbf0b55ce165e797e08105/hironx_ros_bridge/robot/robot-compile-setup.sh#L42) puts the model files from the `models` directory in `nextage_description` package into `/opt/jsk/etc/HIRONX/models`, but the robot system expects the folder to be `model` without "s".

**Comment by k-okada** [comment]
`the robot system` which system?

**Comment by k-okada** [comment]
```
  mv ${TMPDIR}/*/nextage_description/ ${TMPDIR}/opt/jsk/etc/HIRONX
+ mv ${TMPDIR}/opt/jsk/etc/HIRONX/models ${TMPDIR}/opt/jsk/etc/HIRONX/model
```

**Comment by 130s** [comment]
Suggested change was applied in https://github.com/start-jsk/rtmros_hironx/commit/65e033569c26fa97a0810244e980f9b0ec22b370
