### ISSUE TITLE
servoOn on hrpsys dashboard unavailable until HIRONX.init

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#178]
To replicate the issue,
1. robot.goOffPose
2. Tried `servoOn` from dashboard but error dialog pops up. 
   
   Error msg also printed on the ros_bridge terminal (didn't copy the log..) `RobotHardwareROSBridge` returns some errors. 
3. `ipython -i`rospack find nextage_ros_bridge`/script/nextage.py -- --host nextage`
4. Then 2 works as expected.

**Comment by k-okada** [comment]
please copy the log....

**Comment by 130s** [comment]
Pop up says:

```
Failed to servo on:service[/RobotHWSRB/power] responded with an error:
```

Message on the ros_bridge terminal:

```
[rtmlaunch] Wait for  /nextage:15005/sh.rtc:StateHolderService   19 /30
[rtmlaunch] Wait for  /nextage:15005/sh.rtc:StateHolderService   20 /30
[ INFO] [1406200495.141203438]: RobotHardwareServiceROSBridge::power()
omniORB: ERROR -- the application attempted to invoke an operation
 on a nil reference.
[ERROR] [1406200495.141558754]: RobotHardwareServiceROSBridge::power : Caught CORBA::SystemException.
[rtmlaunch] Wait for  /nextage:15005/sh.rtc:StateHolderService   21 /30
[ WARN] [1406200495.956821602]: [HrpsysSeqStateROSBridge0] @onExecutece 0 is not executed last 5[sec]
```

And, I cannot reproduce the error with [the step above](https://github.com/start-jsk/rtmros_hironx/issues/178#issue-38609800). 

I still see this, only when the robot isn't yet calibrated. Do we want to add a feature to allow calibration from the GUI?

**Comment by k-okada** [comment]
that's interesting

```
1. robot.goOffPose
```

does this mean send goOffPose from GUI ? or python, if it is python you already run `HIRONX.init()`??
