### ISSUE TITLE
(robot-compile-openrtm.sh) not installed under designated folder

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#180]
With the PReq https://github.com/start-jsk/rtmros_hironx/pull/179, OpenRTM seems not installed under `/opt/jsk` where it's supposed to be.

```
$ cd /home/sam/openrtm-source-2014-07-26/src/OpenRTM-aist-1.1.0/build/
$ make install
make[1]: Entering directory `/home/sam/openrtm-source-2014-07-26/src/OpenRTM-aist-1.1.0/build'
make[1]: Nothing to be done for `install-exec-am'.
make[1]: Nothing to be done for `install-data-am'.
make[1]: Leaving directory `/home/sam/openrtm-source-2014-07-26/src/OpenRTM-aist-1.1.0/build'
```

In [here](https://github.com/130s/rtmros_hironx/blob/robot_build_openrtm/hironx_ros_bridge/robot/robot-compile-openrtm.sh#L57)

```
PATH=/usr/pkg/bin:/usr/qnx650/host/qnx6/x86/usr/bin:$PATH PKG_CONFIG_PATH=/usr/pkg/lib/pkgconfig CXX=QCC CC=qcc LDFLAGS=\"-L/opt/jsk/lib -L/usr/pkg/lib -lboost_system -lboost_signals -lboost_filesystem -luuid -lsocket -Wl,-u,MAIN__\" CPPFLAGS=\"-I/opt/jsk/include -I/usr/pkg/include -Wall -O2 -I../../include/ \" CXXFLAGS=\"-I/opt/jsk/include -I/usr/pkg/include -Wall -O2 -I../../include/ \" ./configure --host x86-linux-gnu --prefix=/opt/jsk --with-pic=no;
```

`./configure --prefix=/opt/jsk` might be ignored somehow?

**Comment by k-okada** [comment]
ok, i created jenkins server so pleae check -> http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/qnx-hrpsys-build/14/console

I also created patches to download tgz under /tmp/$$ to avoid permission problem, see http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/qnx-hrpsys-build/ws/*.patch for code, and if this is ok, please merge them

**Comment by 130s** [comment]
Code in question is removed from this repo.
