### ISSUE TITLE
(HrpsysConfigurator.saveLog) missing timeframe for the RobotHardware output

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#19]
On 2 of the same robots that run on QNX (Kawada Hiro).

In the saved log after a set of joint movement ([goInitial on Hiro](https://github.com/start-jsk/rtmros_hironx/blob/3206d48f1878ade3c17ff7a0ec35ad8a7113f332/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L123)), there seem to be the time frames that are missing between the state returned from robot and the commanded values.

![gnuplot_hiro_goinit_issuereport_savelog](https://f.cloud.github.com/assets/1840401/2227436/d3728dcc-9ac1-11e3-9a5b-f0f4c360e629.png)

Red line is the actual status while green is command. You can see that red only starts after some point. Once red starts both lines go along (, which is good).

Using `hrpsys` 315.1.7, [hironx_ros_bridge](https://github.com/start-jsk/rtmros_hironx/commit/afa76f62c6f3ec7f07664d5067ff244e8d902ef0)

**Comment by 130s** [comment]
Found with @emijah

**Comment by k-okada** [comment]
please check with this script (`https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/test-hironx-log.py`), you used seq_qRef, which is output only when sequence player interpolates the trajectory. we have to check sh_qOut, which always output command value.
