### ISSUE TITLE
Tutorial improvements

### ISSUE THREAD

**Issue by iory** [start-jsk/rtmros_hironx#195]
**_Update**_ For brevity I (@130s) summarized the following list.
- [x] Split installation into standard and advanced
- [ ] index number of toc is different from that of the body 
- [x] Operation page is confusing. Need a summary.
- [x] Better to have a dedicated page for GUI.
- [x] typo
- [x] Review programming by RTM (`hrpsys`) section
- [x] Add ROS Client tutorial. Currently only RTM client is explained.
- [x] setTargetPose yields error even when no change occurred from the last pose that was made by goInitial

**Comment by iory** [comment]
It is hard to understand that itemization of rtmros_hironx page.
I missed install for Advanced Purposes.
So I think that this page treats a "For Advanced Purposes" another pages.

http://wiki.ros.org/rtmros_nextage/Tutorials/Install%20NEXTAGE%20OPEN%20software%20on%20your%20machine

---

Programming Hiro (Open) / NEXTAGE OPEN
http://wiki.ros.org/rtmros_nextage/Tutorials/Programming
In this page, the number of the table of contents does not match with  the actual number.

**Comment by iory** [comment]
1. Customize behavior in HIRONX / NextageClient
   http://wiki.ros.org/rtmros_nextage/Tutorials/Programming

this tutorial's goal it to change inital position of nextage and hironx.
it is unified by changing 'hironx_client.py"  , it is necessary to modify the tutorial.

**Comment by iory** [comment]
Run sample codes
http://wiki.ros.org/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users
Misspell
 When you're done with work on ipython, press Ctrl-d to escape its comman line.
-> 
 When you're done with work on ipython, press Ctrl-d to escape its command line.

**Comment by iory** [comment]
Operate robot via hrpsys in Python
http://wiki.ros.org/rtmros_nextage/Tutorials/Programming

on ipython, I try following code.
In : pos = robot.getCurrentPosition('RARM_JOINT3')
In : rpy = robot.getReferenceRPY('RARM_JOINT3')
In : tm = 3
In : robot.setTargetPose('rarm', pos, rpy, tm)

 robot.setTargetPose make an error.
if position is not changed, it should not make an error.

**Comment by 130s** [comment]
[Added many improvements](http://wiki.ros.org/rtmros_nextage/Tutorials) so far.

**Comment by 130s** [comment]
- [x] Review programming by RTM (`hrpsys`) section

Added. Up until there, many improvements are added.

**Comment by 130s** [comment]
ROS client programming [is added](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Programming_Hiro_NEXTAGE_OPEN_ROS?action=diff&rev2=6&rev1=5).

**Comment by 130s** [comment]
- > index number of toc is different from that of the body 

I guess this is a `moinmoin` (wiki engine that `ros.org` uses) issue, and I haven't experienced inconvinience so far with this issue. If you still think it's problematic, I'd suggest opening a ticket on [ros wiki issue tracker](https://github.com/ros-infrastructure/roswiki/issues)
- > setTargetPose yields error even when no change occurred from the last pose that was made by goInitial

I was with @iory when he saw this, but I can't replicate the issue now on simulator:

```
term-1$ rtmlaunch hironx_ros_bridge hironx_ros_bridge_simulation.launch 

term-2$ ipython -i `rospack find hironx_ros_bridge`/scripts/hironx.py

In [1]: robot.goInitial(2)
[hrpsys.py] , JntAnglesOfGr=torso, INITPOSE[i]=[0], tm=2, wait=True
[hrpsys.py] , JntAnglesOfGr=head, INITPOSE[i]=[0, 0], tm=2, wait=True
[hrpsys.py] , JntAnglesOfGr=rarm, INITPOSE[i]=[-0.6, 0, -100, 15.2, 9.4, 3.2], tm=2, wait=True
[hrpsys.py] , JntAnglesOfGr=larm, INITPOSE[i]=[0.6, 0, -100, -15.2, 9.4, -3.2], tm=2, wait=True
Out[1]: True

In [15]: posi = robot.getCurrentPosition('LARM_JOINT5')

In [16]: posi
Out[16]: [0.3255627368715471, 0.1823638733778268, 0.07462449717662004]

In [17]: rpy = robot.getCurrentRPY('LARM_JOINT5')

In [19]: robot.setTargetPose('larm', posi, rpy, 3)
larm None [0.3255627368715471, 0.1823638733778268, 0.07462449717662004] (-3.0732189053889805, -1.5690225912054285, 3.0730289207320203) 3
Out[19]: True

```
