### ISSUE TITLE
Models for different Hiro robot versions

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#20]
For `Hiro` robots there are some difference in hardware design: 
- There are at least `Type-B` and `Type-C`, the one that has shorter and longer necks respectively.
- All `Hiro` should be equipped with the same hand. 
- Neck is common b/w `Type-C` and `NEXTAGE OPEN`.

@emijah

**Comment by 130s** [comment]
To avoid having redundancy, is it possible to achieve these within a single ROS model package (eg. create `hironx_description` package) by like:
- Create necessary models and put all into the package
- Shift b/w the combinations of model in `.launch` file

**Comment by 130s** [comment]
Adding another concern:
- The current model file for `Hiro` doesn't include its base.
- Shape of the base is different between newer `Hiro` and older ones (`Type-B`?)

Without base, collision avoidance (eg. `MoveIt!`) works only partially.

**Comment by k-okada** [comment]
closing due to not updating more than a month, please re-open if it still needed
