### ISSUE TITLE
Request for release 1.0.21

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#208]
As discussed in https://github.com/fkanehiro/hrpsys-base/pull/287#issuecomment-51438483, we need to release new version to pass test of hrpsys-base
Feel free to assign me this job if needed

**Comment by k-okada** [comment]
Need to include https://github.com/start-jsk/rtmros_hironx/pull/197  in deb package

**Comment by 130s** [comment]
[Done for Hydro](https://github.com/ros/rosdistro/pull/5248). 

For Groovy, `bloom` complains it cannot find the following package, neither do I on [debuild page](http://www.ros.org/debbuild/groovy.html?q=pr2_control). I guess it might be the time for us to waive Groovy support.

```
Generating debian for precise...
Could not resolve rosdep key 'pr2_controllers_msgs'
Try to resolve the problem with rosdep and then continue.
```

**Comment by k-okada** [comment]
hironx_ros_bridge depend on hrpsys_ros_bridge and  does not have to directory depends on hrpsys, pr2_controllers_msgs, they are depended from hrpsys_ros_bridge.

**Comment by k-okada** [comment]
see https://github.com/start-jsk/rtmros_hironx/pull/211
