### ISSUE TITLE
python version of acceptancetest_hironx.cpp

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#226]
@iory Today, you showed me python version of acceptancetest_hironx, but I forget the file name, could you tell me that again?

**Comment by iory** [comment]
python version of acceptancetest_hironx is here.
https://github.com/start-jsk/rtmros_hironx/tree/groovy-devel/hironx_ros_bridge/scripts

**Comment by k-okada** [comment]
thanks @iory, 
@130s how can I use this script? Will `python ./acceptancetest_hironx.py` work?

**Comment by 130s** [comment]
> how can I use this script? Will python ./acceptancetest_hironx.py work?

This is documented in [quick start](http://wiki.ros.org/rtmros_nextage/Tutorials/Quick%20Start%20for%20Robot%20Users#Run_the_Delivery_Inspection_script).

**Comment by k-okada** [comment]
thanks
