### ISSUE TITLE
update tutorial order, split programming sections

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#237]
currently http://wiki.ros.org/rtmros_nextage/Tutorials/Programming says
Programming Hiro / NEXTAGE OPEN (RTM), but actually it contains how to move robot from moveit interface, may be following seems better.

```
0. Interact with Hiro / NEXTAGE OPEN (MoveIt GUI)
1. Programming Hiro / NEXTAGE OPEN (RTM),
2. Programming Hiro / NEXTAGE OPEN (ROS),
3. Programming Hiro / NEXTAGE OPEN (MoveIt),
```

**Comment by k-okada** [comment]
I split original document into 4 different tutorials, how do you think?
If this is better, then remove these documents from http://wiki.ros.org/rtmros_nextage/Tutorials/Programming, and te title of this pages is (Programming Hiro / NEXTAGE OPEN) and add link to 4 new tutorials.

**Comment by k-okada** [comment]
@130s, I have updated the tutorial (just split into 4 different tutorials) without getting permission, if it does not looks good, please say so.

By the way, how to change the order for http://wiki.ros.org/rtmros_nextage/Tutorials ?
I prefer 

```
 Programming Hiro / NEXTAGE OPEN
 Interact with Hiro / NEXTAGE OPEN (MoveIt GUI)
 Programming Hiro / NEXTAGE OPEN (RTM),
 Programming Hiro / NEXTAGE OPEN (ROS),
 Programming Hiro / NEXTAGE OPEN (MoveIt),
```

I also would like to add section like http://wiki.ros.org/rocon_app_manager/Tutorials

```
For everyone..
1. Install Hironx/NEXTAGE OPEN API software on your machine
2. Troubleshooting
3. Support, Contribution

For Hardware owners...
1. Quick Start for Robot Users
2. Operating Hiro/NEXTAGE OPEN Monitoring and operating via GUI
3. Operation on QNX
4. Changing Grippers on Nextage Hardware

For Software developers...
1. Programming Hiro / NEXTAGE OPEN
2. Programming Hiro / NEXTAGE OPEN (RTM)
3. Programming Hiro / NEXTAGE OPEN (ROS)
4. Programming Hiro / NEXTAGE OPEN (MoveIt Python Commander)
5. Programming Hiro / NEXTAGE OPEN (GUI)
6. Advanced installation Hironx/NEXTAGE OPEN API software
7. Changing Nextage Grippers in Robot Model
8. Adding feedback control
9. How to control a robot application from Android.
```

**Comment by 130s** [comment]
> By the way, how to change the order for http://wiki.ros.org/rtmros_nextage/Tutorials ?

I [added this to the ROS tutorial](http://wiki.ros.org/action/info/ROS/Tutorials/NavigatingTheWiki?action=diff&rev2=53&rev1=52#To_create_tutorial_pages_under_your_package). 

And I re-ordered the contents of NXO tutorials. Sorry I didn't see your list when I made a change...how does this look?
http://wiki.ros.org/action/info/rtmros_nextage/Tutorials?action=diff&rev2=4&rev1=2

**Comment by k-okada** [comment]
very nice!!!

**Comment by 130s** [comment]
Re-ordering and split is done.

Btw I'm basically re-structuring the entire tutorial pages. Now almost done with `introductory level` pages.
