### ISSUE TITLE
hironx_moveit_config 1.0.23 does not build on Groovy

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#238]
http://jenkins.ros.org/view/GbinP64/job/ros-groovy-hironx-moveit-config_binarydeb_precise_amd64/110/console

```
-- Python version: 2.7
-- Using Debian Python package layout
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/buildd/ros-groovy-hironx-moveit-config-1.0.23-1precise-20140904-0536/obj-x86_64-linux-gnu/test_results
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- catkin 0.5.89
CMake Error at /opt/ros/groovy/share/hironx_ros_bridge/cmake/hironx_ros_bridgeConfig.cmake:141 (message):
  Project 'hironx_moveit_config' tried to find library 'ros_client_cpp'.  The
  library is neither a target nor built/installed properly.  Did you compile
  project 'hironx_ros_bridge'? Did you find_package() it before the
  subdirectory containing its code is included?
Call Stack (most recent call first):
  /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/groovy -DCMAKE_PREFIX_PATH=/opt/ros/groovy returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory `/tmp/buildd/ros-groovy-hironx-moveit-config-1.0.23-1precise-20140904-0536'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
W: no hooks of type C found -- ignoring
I: unmounting /var/cache/pbuilder/ccache filesystem
I: unmounting dev/pts filesystem
```

Looks like [in building `hironx_ros_bridge`](http://jenkins.ros.org/view/GbinP64/job/ros-groovy-hironx-ros-bridge_binarydeb_precise_amd64/76/consoleFull), `ros_client_cpp` isn't built (it DOES get built on hydro build though).

**Comment by k-okada** [comment]
I have fixed this one in https://github.com/tork-a/rtmros_hironx-release/commit/6a722ad9a0b0c1a8076fb251150a4b04140ce4e2

**Comment by k-okada** [comment]
I see, i forget to remove  https://github.com/tork-a/rtmros_hironx-release/blob/debian/groovy/hironx_ros_bridge/catkin.cmake#L11

**Comment by k-okada** [comment]
fixed, see https://github.com/tork-a/rtmros_hironx-release/blob/debian/groovy/hironx_ros_bridge/catkin.cmake#L11

**Comment by 130s** [comment]
Or...can we simply withdraw Groovy package, maybe by downgrading to the previous version `1.0.22`?

**Comment by 130s** [comment]
> fixed, see https://github.com/tork-a/rtmros_hironx-release/blob/debian/groovy/hironx_ros_bridge/catkin.cmake#L11

I see. I'll re-release only for Groovy with build increment.

**Comment by k-okada** [comment]
I have already releaesd as https://github.com/tork-a/rtmros_hironx-release/commit/d9887cb347e97e904ac42dcb59c63483df5a5e66 1.0.23-2

**Comment by 130s** [comment]
> I have already releaesd as tork-a/rtmros_hironx-release@d9887cb 1.0.23-2

(ﾟдﾟ)！That's what I'm wondering. So now I think we just need to notify rosdistro. I'm on it.

**Comment by k-okada** [comment]
> So now I think we just need to notify rosdistro. I'm on it.

Oh, yes, I forget about that. Thanks.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/5511
