### ISSUE TITLE
To cancel the trajectory (hrpsys, MoveIt!)

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#250]
In a trial to implement `stop` feature discussed in #36, I'm trying to utilize existing methods to achieve (1) stopping the arm that's moving according to the given trajectory, (2) canceling the given trajectory. (2) may or may not be critically in need depending on the situation. 
I tried the following both on `MoveIt!` and `hrpsys`. Neither worked to my expectation. What's the right way to do so?

**_MoveIt!**_

```
term-1$ rtmlaunch hironx_ros_bridge hironx_ros_bridge_simulation.launch 

term-2$ roslaunch hironx_moveit_config moveit_planning_execution.launch 

term-3$ ipython -i `rospack find hironx_ros_bridge`/scripts/hironx.py
```

Then move an arm by MoveIt!, maybe using RViz plugin's `random` feature. While the arm is moving, ran:

```
In [2]: robot.servoOff()  # I know I'm on simulation.
In [3]: robot.clear()
```

**_hrpsys**_

```
In [49]: robot.goInitial(1.5)
:
Out[49]: True

In [50]: pose_r
Out[50]: 
[0.9998309638508134,
 -0.006003459001414185,
 -0.017378210643564852,
 -0.06430055471859833,
 0.0009817197259366591,
 0.9612723882086925,
 -0.27559831620301467,
 -0.08785886673095027,
 0.01835973724031689,
 0.27553466959273104,
 0.9611157921399955,
 -0.21089215061362426,
 0.0,
 0.0,
 0.0,
 1.0]

In [51]: robot.setJointAnglesOfGroup('rarm', pose_r, tm, False)
Out[51]: True

In [52]: robot.servoOff()
[hrpsys.py]  omit servo off
Out[52]: 0

In [53]: robot.clear()
```

**Comment by k-okada** [comment]
i think `clear()` clears queued waypoins, so you'd better to send command
with several way points using TrajectorJjointAction of ros interface and
MoveIt uses that.

**Comment by 130s** [comment]
Addressed in several ways incl. https://github.com/fkanehiro/hrpsys-base/pull/665, https://github.com/tork-a/rtmros_nextage/issues/284
