### ISSUE TITLE
Create HiroNXO dashboard

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#261]
Mentioned in https://github.com/start-jsk/rtmros_common/issues/548#issuecomment-57271703 to add joint calibration button.

**Comment by k-okada** [comment]
This is how to servo on / servo of through ros service -> https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/hrpsys_ros_bridge/hrpsys_dashboard.py#L125

**Comment by 130s** [comment]
Fyi @DaikiMaekawa how to send hrpsys/RTM command over ros service (eg. [turning on servo](https://github.com/start-jsk/rtmros_common/blob/d0c3874fec974d7fa9d27cf47c76560e40723da2/hrpsys_ros_bridge/src/hrpsys_ros_bridge/hrpsys_dashboard.py#L160)).

**Comment by 130s** [comment]
Addressed in https://github.com/start-jsk/rtmros_hironx/pull/317
