### ISSUE TITLE
To reboot QNX

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#273]
[Reboot instruction in wiki](http://wiki.ros.org/rtmros_nextage/Tutorials/Operation%20on%20QNX#Reboot_QNX) returns an error. 

```
QNX$ su -c '//bin/shutdown'
ldd:FATAL: Could not load library libomniORB4.so.1
```

Seen on a Hiro robot with hrpsys 315.1.7 running.

@emijah

**Comment by emijah** [comment]
@130s これはNextageでインストールされる、特別バージョンのshutdownコマンドですね。
QNXでパッケージングされているshutdownコマンドは/bin/shutdown_bakにリネームされています。

libomniORB4.so.1をリンクしているところからお分かりになると思いますが、このバイナリはCORBA
サーバを一度停止してからshutdownを実行するようになっています。これはCORBAサーバにKILLシグナルを送った場合、そのままハングしてしまうケースが発生したためです。CORBAのバージョンをあげておくとハングすることはほぼなくなります。

**Comment by 130s** [comment]
I see, I confirmed that this works on NXO. [Added a note on wiki](http://wiki.ros.org/action/info/rtmros_nextage/Tutorials/Operation%20on%20QNX?action=diff&rev2=10&rev1=9).
