### ISSUE TITLE
Where have stereo camera frames gone?

### ISSUE THREAD

**Issue by youtalk** [start-jsk/rtmros_hironx#277]
When I checked `rosrun tf view_frames` few months ago, I could find stereo camera frames on the head like following image.

![](https://cloud.githubusercontent.com/assets/579333/4713813/e7675cb0-58e7-11e4-952c-323a3d83c70c.png)

But now I cannot find the camera frames. Where have they gone?

**Comment by k-okada** [comment]
https://raw.githubusercontent.com/start-jsk/rtmros_hironx/hydro-devel/hironx_ros_bridge/models/kawada-hironx.dae
does not have camera information and that is not changed for more than 1
year, so I do not think we have camera-related tf frame 1 month ago.

**Comment by youtalk** [comment]
Hmm... I got it. I'll make a PR about it.

**Comment by youtalk** [comment]
Sorry I reopened this issue. 

Which do we need to append camera-related info to [HiroNX.urdf](https://github.com/start-jsk/rtmros_hironx/blob/hydro-devel/hironx_moveit_config/models/HiroNX.urdf) or [kawada-hironx.dae](https://raw.githubusercontent.com/start-jsk/rtmros_hironx/hydro-devel/hironx_ros_bridge/models/kawada-hironx.dae)? The urdf file is generated from the collada file or vice versa? I'm confusing. See also https://github.com/start-jsk/rtmros_hironx/issues/100

**Comment by k-okada** [comment]
urdf is generated from dae and dae file is generated from wrl. but wrl is
not disclosed.
so we took dae from
https://github.com/rdiankov/openrave/tree/master/src/robots

easiest way is to put hiro wrl file to somewhere or change hiro wrl and
create dae file and put it in somewhere.

**Comment by youtalk** [comment]
Thank you. It's informative.
You imply `rtm_hironx` package actually should contain wrl files of HIRONX, right?
Because `rtm_nextage` package contains wrl files of NEXTAGE OPEN.

**Comment by emijah** [comment]
Ah, I remember handing that file to Rosen quite a long time ago. I converted the wrl files that the current Nextage Open relies on, so that is where the camera coordinates come from...

**Comment by k-okada** [comment]
Yes, that what I expected and required, but manufacture did not gave us 
permission. Please ask them again.

**Comment by emijah** [comment]
Okay

**Comment by youtalk** [comment]
@emijah found `CAMERA_HEAD_R` and `CAMERA_HEAD_L` elements in [nextage.dae](https://raw.githubusercontent.com/tork-a/rtmros_nextage/hydro-devel/nextage_ros_bridge/models/nextage.dae). I think HrpsysSeqStateROSBridge cannot parse those elements then camera-related frames dispappear. 

On the other hand, there is no `CAMERA_HEAD_R` and `CAMERA_HEAD_L` elements in [kawada-hironx.dae](https://raw.githubusercontent.com/start-jsk/rtmros_hironx/hydro-devel/hironx_ros_bridge/models/kawada-hironx.dae). We should append those elements.

**Comment by emijah** [comment]
@youtalk actually I found the entries for the cameras in /opt/ros/hydro/share/nextage_description/models/main.dae. So VRML -> Collada seems to be working. 
I took a look at ros/robot_model and found the following in robot_model/collada_parser/src/collada_parser.cpp:

```
   /// \brief Extract Sensors attached to a Robot
    void _ExtractRobotAttachedSensors(const domArticulated_systemRef as)
    {
        ROS_DEBUG("collada sensors not supported yet");
    }
```

so, if sensor information is being extracted from collada and saved to urdf, this may cause problems.

**Comment by k-okada** [comment]
On Tue, Nov 4, 2014 at 3:36 PM, Yutaka Kondo notifications@github.com
wrote:

> I found CAMERA_HEAD_R and CAMERA_HEAD_L elements in nextage.dae
> https://raw.githubusercontent.com/tork-a/rtmros_nextage/hydro-devel/nextage_ros_bridge/models/nextage.dae.
> I think HrpsysSeqStateROSBridge cannot parse those elements then
> camera-related frames dispappear.

That's good point, if ROSBRIDGE include CAMERA_\* in /joint_states, I think
it should work as you expected. Please write small program that publish
joint_states only for camera related joints and confirm them.
Next thing is we have to consider this function in ROSBridge, at this
moment I'm not sure about side-effects of this change. Please open a issue
to rtmros_common

**Comment by youtalk** [comment]
Thank you. I've got it.
