### ISSUE TITLE
After checkEncoders white lamp still blinks

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#35]
@emijah 

Not happening always but I've seen the following that occurred at the same situation:
- After `robot.checkEncoders()`, bumpy move that's supposed to happen twice only occurred once.
- The usual output like following didn't print:

```
[hrpsys.py] calib-joint all
[hrpsys.py] done
Turn on Hand Servo
```
- Then at the chest lamp, green turned on but white still blinks. The combination I don't find in the h/w manual.
- Servo seems to be on (I knew by touching arms)

I worked it around by:
- `robot.servoOff` and `checkEncoders` again.

What didn't work:
- `slay rtcd` on QNX

No suspicious log in `rtcd.log`. What is it?

**Comment by emijah** [comment]
@130s 
Could you please send us the log files in /opt/hiro/log/
I've never heard of this one before.
Is this the old Hiro or newer Hiro?
Are both cores visible? I'm wondering because the closest thing I've heard was the problem with the single core kernel booting in the robot.

**Comment by 130s** [comment]
> Could you please send us the log files in /opt/hiro/log/

Thank you for the concern. Here's tarball from the end of that day you
should be having an access right to it:
https://drive.google.com/#folders/0Bw_hbVS3wTLyX1lzcm9GUWNTRUU
If more data may be needed I can ask the user for it.
