### ISSUE TITLE
[Call for volunteer] Robot page on roswiki

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#369]
By following the defacto standard on the ["Robots" page on ROS wiki](http://wiki.ros.org/Robots), I finally created HiroNXO page. 

http://wiki.ros.org/Robots/HiroNXO

Please have a look and add any necessary change.

There's no "rule" per se but here's what I stick to:
- Focus is on software, but decent info on hardware is probably appreciated by the readers
- List capabilities and ROS-formatted name of modules so that readers on that site easily have ideas of what features available in ROS can be used with this robot
- No too commercial promotion (respect that ROS wiki is opensource communication platform)

One of the things especially appreciated is the feature-by-feature images.

**Comment by 130s** [comment]
I close this ticket but please feel free to make/suggest changes.

**Comment by k-okada** [comment]
nice!!

## 

◉ Kei Okada

**Comment by emijah** [comment]
Can't think of anything to add at this point...
