### ISSUE TITLE
create GUI that restart QNX / rtcd

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#37]
create GUI that just start following scripts:

https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/robot/reboot-robot.sh
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/robot/restart-controller.sh

**Comment by 130s** [comment]
Not sure but https://github.com/start-jsk/rtmros_common/pull/434 may have addressed this? I'll test it anyway.

**Comment by 130s** [comment]
Continued in https://github.com/start-jsk/rtmros_hironx/issues/138
