### ISSUE TITLE
Release request for new version.

### ISSUE THREAD

**Issue by snozawa** [start-jsk/rtmros_hironx#394]
Release request for new version to include https://github.com/start-jsk/rtmros_hironx/pull/393.
hrpsys-base test uses `ros-hydro-hironx-ros-bridge` from deb.

**Comment by 130s** [comment]
Work in progress

**Comment by 130s** [comment]
Done for hydro https://github.com/ros/rosdistro/pull/9430
Thank you for the update @snozawa.

**Comment by snozawa** [comment]
Thank you!
I wait for deb update.
