### ISSUE TITLE
hironx_ros_bridge failed to find openhrp3

### ISSUE THREAD

**Issue by garaemon** [start-jsk/rtmros_hironx#40]
I have this error message:

```
-- +++ processing catkin package: 'hironx_ros_bridge'
-- ==> add_subdirectory(rtm-ros-robotics/rtmros_hironx/hironx_ros_bridge)
-- checking for module 'openhrp3.1'
--   package 'openhrp3.1' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  rtm-ros-robotics/rtmros_hironx/hironx_ros_bridge/catkin.cmake:25 (pkg_check_modules)
  rtm-ros-robotics/rtmros_hironx/hironx_ros_bridge/CMakeLists.txt:2 (include)
```

I try to build hironx_ros_bridge with openhrp3 without using apt package.

in [travis-ci](https://travis-ci.org/start-jsk/rtmros_hironx), it compile hironx_ros_bridge with openhrp3 apt package.
it means `pkg_check_modules(openhrp3)` runs successfully, but when we use openhrp3 in src directory, hironx_ros_bridge missing dependency to openhrp3.

**Comment by 130s** [comment]
Ah, okay. From dependency graph, I can see `hironx_ros_bridge` depends on `openhrp3` only via `hrpsys_ros_bridge --> hrpsys` chain.

![dependency_hironx_ros_bridge_transitive_to_openhrp3](https://f.cloud.github.com/assets/1840401/2306384/06044e1e-a284-11e3-9a73-063282ec5f87.png)

**Comment by 130s** [comment]
Or I'm confused. Is this ticket talking about separate issue from [the comment here](https://github.com/start-jsk/rtmros_hironx/pull/30#commitcomment-5535604)?

**Comment by k-okada** [comment]
yes, this ticket was solved in https://github.com/start-jsk/rtmros_hironx/commit/827ecd290e29125576895b1997c85d69795472af, sorry for confusion.

% rqt_dep is so useful!!
