### ISSUE TITLE
hironx.py connection inter-host; RobotHardware wasn't found 

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#435]
On `Host1`: Running `rtmlaunch hironx_ros_bridge hironx_ros_bridge_simulation.launch`
On `Host2`: "ipython -i `rospack find hironx_ros_bridge`/scripts/hironx.py -- --host Host1"

`RobotHardware` wasn't found error happened. These 2 hosts are in the same LAN.

**Comment by k-okada** [comment]
--host must be target to the RTM name server name, not HOST1_NAME,
if you wan to connect ROS client in hironx.py to ROS master running at
HOST1_NAME,
use ROS_MASTER_URI as always.

## 

◉ Kei Okada

**Comment by 130s** [comment]
I've updated my original post for clarification. I don't think I used a wrong RTM host name.

`ping` worked between the hosts.

**Comment by k-okada** [comment]
Oh, you're using simulation ,
In that case you have to manually specify `--robot HiroNX(Robot)0` to override 
https://github.com/start-jsk/rtmros_hironx/blob/indigo-devel/hironx_ros_bridge/scripts/hironx.py#L66

**Comment by 130s** [comment]
Thanks you for the clarification.

[Added to wiki](http://wiki.ros.org/rtmros_nextage/Tutorials/Run%20simulation#Connecting_to_a_simulated_robot_running_on_a_remote_host) as well.
