### ISSUE TITLE
[HIRONX python] hrpsys version checking codes not necessary?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#444]
Lots of comments in https://github.com/start-jsk/rtmros_hironx/pull/443

**Comment by k-okada** [comment]
what i understand so far
- version checking is done on upstream, but it raises error
- this may trouble on hironx override implementation, that force set "WAIST" as default frame (so it always call function with frame_name, even if old hrpsys, and it rises error)

#445 changed the HrpsysConfigurator just print out warning, not raises error, also support default frame_name , see if this pass the test.

**Comment by 130s** [comment]
Looks like fixed in #445 #455
