### ISSUE TITLE
What for are .conf.in and .xml.in files, and how are they used to generate .conf files?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#46]
[Example](https://github.com/start-jsk/rtmros_hironx/tree/188065bd2174d153f4b2f6b8728b5ff50c2bf430/hironx_ros_bridge/conf)

Once I understand, I can document this somewhere reasonable.

**Comment by k-okada** [comment]
conf files are openrtm-related configuration files, see [1] for example and [2] for documents. These files needs absolute path to the model file andd plugin libraries so we need to use configure_file to generate on the fly, also when we copy them from devel space to install space, we need to use sed to fix the path.

xml file is openhrp3 `project file` (see [3]) and now used to configure simulation environment, it also requires model file locaiton

[1] https://github.com/start-jsk/hrpsys/blob/master/test/test-pa10.test
[2] http://www.openrtm.org/openrtm/ja/content/%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB-%E5%9F%BA%E7%A4%8E%E7%B7%A8
[3] http://www.openrtp.jp/openhrp3/3.0.2/jp/grxui_tutorial.html

**Comment by 130s** [comment]
Documented [here](http://wiki.ros.org/rtmros_nextage/Tutorials/Changing%20Nextage%20Grippers%20in%20Robot%20Model#A.conf_and_.xml_files_in_conf_directory).
