### ISSUE TITLE
Color me! Model

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#48]
From https://github.com/start-jsk/rtmros_common/issues/132

**Comment by k-okada** [comment]
is there any specific request for this? which robot? which parts?? or more general question?

**Comment by 130s** [comment]
> is there any specific request for this? which robot? which parts?? or more general question?

This wasn't a request to change color of the current models; a user is interested in working on it instead. We might just want to provide info on how to do so. 

[Related](https://github.com/start-jsk/rtmros_hironx/issues/56).
