### ISSUE TITLE
Use both arms simultaneously in MoveIt!

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#53]
Asked by a new user to `hironx` package.

So there's a discussion in [MoveIt! ML](https://groups.google.com/d/msg/moveit-users/vV5GR2kFR9o/7Bmrs7M1D2MJ) to achieve this. If someone gives a shot and shares how to do so would be greatly appreciated.

**Comment by 130s** [comment]
[This pending pull request](https://github.com/ros-planning/moveit_ros/pull/431) in MoveIt! upstream is related. I assume that ultimately we want to depend on this new feature.

**Comment by k-okada** [comment]
closing due to https://github.com/ros-planning/moveit_ros/pull/431 has been merged, please reopen if you need this.
