### ISSUE TITLE
Can waist be added to (multilple) arm joint groups?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#54]
Asked by a new user who wonders to include waist into the capability of both  arm groups. I think we need to think separately for `hrpsys` and `MoveIt!`.

**Comment by k-okada** [comment]
yes, i think we can do that.

**Comment by 130s** [comment]
Just improved the title to clarify what's needed.

Okay, then I'll give it a shot with hironx later.

**Comment by k-okada** [comment]
Do you mean that waist is shared by both arm? in that case, you may need https://github.com/ros-planning/moveit_ros/pull/431#issuecomment-36915077 and fullbody-ik. But currently there are no fullbody ik whcih is easy to use. so you may better to create one arm with waist and one arm without waist and create both arms' joint group

**Comment by 130s** [comment]
> Do you mean that waist is shared by both arms?

That's what I thought.

I see for MoveIt! workaround.

How about hrpsys?

**Comment by k-okada** [comment]
@snozawa , can you comment on this? there might be code to do this within autobalancer or somewhere?

**Comment by adolfo-rt** [comment]
If the goals are given in joint space, you can already create different planning groups containing the torso (arm, left-arm+torso, right-arm+torso, both-arms+torso), and they can coexist. If goals are specified in task-space, you can already plan for single end-effector groups like arm+torso, but if you want task-space goals for multiple end-effectors (both-arms+torso), ros-planning/moveit_ros#431 would be required.

**Comment by snozawa** [comment]
> there might be code to do this within autobalancer or someware?

Currently not implemented yet in hrpsys-base/rtc/ImpedanceController/JointPathEx.cpp.
(Moreover, autobalancer is not fully migrated from JSK local repositiory to hrpsys-base repository.)

For this purpose, we just concatenate Jacobian matrix for left-arm+torso and right-arm+torso.
