### ISSUE TITLE
How does RViz receive from MoveIt! the collision data?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#55]
This isn't a specific issue/question to hironx at all; it's rather my homework that's asked by a new hironx user.

I guess it's what [FCL returns](http://answers.ros.org/question/70822/questions-about-moveit-collision-detection/). I need to study. Don't touch. Comments welcomed though.

The new user above is wondering if there's an interface in `MoveIt!` (or directly from `FCL` if my guess is appropriate) to access the collision information, it would become possible in `hrpsys` or any program to do their own collision avoidance without depending on `move_group`.

**Comment by k-okada** [comment]
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/scripts/collision_state.py with https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/launch/collision_detector.launch launch file is the good example of how to get collision state. I'm not sure on MoveIt case.

**Comment by 130s** [comment]
> https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/scripts/collision_state.py with https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/launch/collision_detector.launch launch file is the good example of how to get collision state. I'm not sure on MoveIt case.

Thank you, for `hrpsys` collision detection (once hrpsys collision detection is sufficiently enabled on hiro (ie. #36, and maybe a few more tickets) I think I'll have to document it).

For MoveIt!, the following diagram from [Overview page](http://moveit.ros.org/wiki/Environment_Representation/Overview#Collision_Checking) explains well.

<img src = "http://moveit.ros.org/distros/current/w/images/9/9b/Planning_scene_monitor_diagram.png" />

**Comment by 130s** [comment]
Looks like through [Planning Scene](http://docs.ros.org/hydro/api/pr2_moveit_tutorials/html/planning/src/doc/planning_scene_ros_api_tutorial.html) in MoveIt! you can get a trigger of when the collision occurs in C++. See [tutorial](http://moveit.ros.org/wiki/Environment_Representation/C%2B%2B_API#Getting_Contact_Information).

My guess is that combining something like follwoing would do:
1. Watch if collision happens by `collision_result.collision`.
2. Once it does, get the pose info via `/move_group/monitored_planning_scene` topic.
