### ISSUE TITLE
Clarify how to convert into .wrl on Solidworks

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#56]
A usergroup is wondering if it's easy to convert their model into `.wrl`. 
Though I'm not entirely sure if we should, it maybe user-friendly to add these kinds of info on [the tutorial](http://wiki.ros.org/rtmros_nextage/Tutorials/Changing%20Nextage%20Grippers%20in%20Robot%20Model#Prepare_Hand_Model).

**Comment by emijah** [comment]
A full recipe is probably difficult so it may turn into a series of tips.

**Comment by YoheiKakiuchi** [comment]
One solution is using meshlab described below
https://forum.solidworks.com/thread/44730

**Comment by emijah** [comment]
Nice
