### ISSUE TITLE
Does Futaba hand RTC bundled in grx controller work with rtmros_hironx?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#57]
A user who's switching to opensource controller is wondering. If so, how can it be achieved?

**Comment by 130s** [comment]
@emijah

**Comment by k-okada** [comment]
https://code.google.com/p/hrpsys-base/source/browse/#svn%2Ftrunk%2Frtc%2FServoController might work.

**Comment by k-okada** [comment]
we created this RTC based on this manual. http://www.futaba.co.jp/dbps_data/_material_/localhost/robot/servo/manuals/RS301CR_RS302CD_114.pdf

if users uses same modules, it should work.

**Comment by emijah** [comment]
Sorry @130s, I need to check github more frequently. Yes, @k-okada is right. Futaba servo drives should work. So long as the software stays away from "special" functions in the Futaba protocol, all Futaba servo drives should function properly.

**Comment by 130s** [comment]
Thank you, now closing.
For how to use hands, [this PReq](https://github.com/start-jsk/rtmros_hironx/pull/66) adds a little more api doc in HIRONX class that accesses `hrpsys`.`ServoController` to send hand commands to the hardware, and this should enable `Futaba` device.
