### ISSUE TITLE
Review hironx-nextageopen system component diagram for users

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#59]
Please review @k-okada, and anyone who's interested in I'll give edit right if you request against. You know I'm so bad at drawings.
https://docs.google.com/drawings/d/12jyX6fGuVDiIJpACxixHhZ_Z8IdO1yIcJhkkrJ7B0Pk/edit?usp=sharing

Doesn't have to be completely detailed but needs to be exhaustively and collectively descriptive for the robot users.

**Comment by 130s** [comment]
Diagram updated.

<img src="https://docs.google.com/drawings/d/12jyX6fGuVDiIJpACxixHhZ_Z8IdO1yIcJhkkrJ7B0Pk/pub?w=960&amp;h=720">

**Comment by k-okada** [comment]
Sorry for late, that seems better,
1) what's is the difference between Uses/Sends
2)  It may depends on how you interpret this diagram, but hrpsys(rtcd) does not run Ubuntu side, it is running on QNX side
- use different shape for different concept / layer
-  1) two main concept is QNX/Ubuntu hardware machine  and ROS/OpenRTM communication world
-  2) then we have package name layer (openrtm_aist, hrpsys, openhrp3, hironx_ros_bridge,,,,)
-  3)  then we have executable program or script file name layer
-  4) we may have library layer between 2 and 3 (OpenHRP3 libraries, or using hironx_client.py as modules)
-  5) we can create message layer that indicate what kind of messages are send between programs.

**Comment by 130s** [comment]
Though not complete, I changed a lot. The image in the previous comment should reflect the change.
