### ISSUE TITLE
Head angle differs per type of Hiro

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#62]
This is a hardware difference, not a problem. I'm not sure at all if this would cause any issue. Just raising an attention here since I was asked by one of the users.

`Type-B` robot looks straight ahead ![hiro](http://wiki.ros.org/hironx_ros_bridge?action=AttachFile&do=get&target=hiro_before_move_rarm.png)

`Type-C` (incl. `NXOpen`) looks slightly down: ![nxopen_hrpsys-viewer](https://f.cloud.github.com/assets/1840401/2373870/58087b4e-a857-11e3-810c-cf0de0bd3895.png)

Assuming at both poses above `pitch` is 0 degree at head joint, there maybe possible problems for the users who own both Type B and C (eg. application that uses head angle of initial pose looks).

**Comment by k-okada** [comment]
closing. if we still need some action for this, please reopen this ticket
