### ISSUE TITLE
hironx_moveit_config does not depend on collada_tools

### ISSUE THREAD

**Issue by garaemon** [start-jsk/rtmros_hironx#65]
package.xml miss dependency to collada_tools and catkin_make says:

```
[rospack] Error: stack/package collada_tools not found
make[2]: *** [/home/jskuser/ros/groovy_catkin/src/rtm-ros-robotics/rtmros_hironx/hironx_moveit_config/models/HiroNX.urdf] Error 2
make[1]: *** [rtm-ros-robotics/rtmros_hironx/hironx_moveit_config/CMakeFiles/hironx_moveit_config_HiroNX_urdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by 130s** [comment]
Before adding `collada_tools` to `package.xml`, can I ask what is the most appropriate way to obtain the package? Its ROS `deb` doesn't seem to have been released yet and I'm afraid depending on it might not pass the buildfarm.

**Comment by k-okada** [comment]
collada_tools is not released yet [1], and since we'd like to release rtmros_hironx, we'd better not to depend to collada_tools.

[1] https://github.com/jsk-ros-pkg/jsk_model_tools/issues/14

**Comment by k-okada** [comment]
@YoheiKakiuchi how different collada_urdf of 
https://github.com/ros/robot_model/tree/indigo-devel/collada_urdf/src and https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/collada_tools/src/collada_to_urdf.cpp, can we use robot_model version of collada_urdf for oridinaly users? if not we have to release and maintain  jsk_model_tools very carefully

**Comment by 130s** [comment]
There's no immediate need for releasing new version of hironx at the
moment, but I expect there'll soon be.

**Comment by k-okada** [comment]
I noticed that we did discussed same issune on 
https://github.com/start-jsk/hironx-package/issues/28#issuecomment-23391729
;-9

**Comment by YoheiKakiuchi** [comment]
https://github.com/ros/robot_model/tree/indigo-devel/collada_urdf/src and https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/collada_tools/src/collada_to_urdf.cpp are the same program.
collada_to_urdf.cpp is not exist in groovy-devel, so collada_to_urdf.cpp in jsk-ros-pkg is reamining.

**Comment by 130s** [comment]
I'm not sure if I understand correctly, but then can we replace `collada_tools` with `collada_urdf` on G and H like this?
- (current) `rosrun collada_tools collada_to_urdf <input-urdf> <output.dae>`
- (new) `rosrun collada_urdf collada_to_urdf <input-urdf> <output.dae>`

(I'm still figuring out why catkin `hironx_moveit_config` on buildfarm passes where `collada_tools` shouldn't be available.)

**Comment by k-okada** [comment]
I think so. 

And collada_tools will replaced by collada_urdf_jsk_patch

https://github.com/jsk-ros-pkg/jsk_model_tools/issues/20
