### ISSUE TITLE
Install scripts in robot folder

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#76]
@k-okada Is there any reason why the scripts in [hironx_ros_bridge/robot](https://github.com/start-jsk/rtmros_hironx/tree/groovy-devel/hironx_ros_bridge/robot) are not installed?

**Comment by k-okada** [comment]
No, I just forget.

**Comment by 130s** [comment]
I see, will be added shortly

**Comment by k-okada** [comment]
Yes please, but I didn't finalize(confirmed) these script yet, maybe we'd better to test them on https://github.com/start-jsk/rtmros_hironx/issues/75

**Comment by k-okada** [comment]
For example, https://github.com/tork-a/hironx-package/commit/60f5e3c5e81199d23e33bdef4472d984789e5743#commitcomment-5457997 said that 

```
/opt/hiro/bin/start_hiro_jsk.sh
```

should invoke

```
cd /opt/hiro/bin
./shared init
./shm_iob_hiro 
```

but current version of 
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/robot/startJSK.sh.in
still execute `shm_iob_hiro`.

**Comment by 130s** [comment]
Got it. We'll wait
