### ISSUE TITLE
Add sample code

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#79]
Originally pinged here https://github.com/jsk-ros-pkg/jsk_recognition/issues/52#issuecomment-40711011

Currently there's not much sample codes out there, not huge package either, so putting them into an existing package should be enough (once we have more samples, separating package will give us flexibility).

**Comment by 130s** [comment]
Overturning what I said above, [a deciaion is made](https://github.com/tork-a/delivery/issues/8#issuecomment-41382706) to create a new package specifically for sample code. `hironx_demo` in `rtmros_hironx` suite?

**Comment by k-okada** [comment]
That's seems ok,

My original idea is to create new `repository` (sorry that I confused in https://github.com/tork-a/delivery/issues/8#issuecomment-41382706)  so that when ever we run the test code for that repository (via travis or jenkins), it checks if delivered deb works with demo code.

I basically do not like to increase the number of repository, because it is hard to maintain. if you like above idea, we can create new repo.

repo, package, Both is fine for me

**Comment by k-okada** [comment]
so users will launch 

jsk_pcl_ros/launch/openni_local.launch in the robot (the machine connected to the device)

and

jsk_pcl_ros/launch/openni_remote.launch in the machine that is remote from the real robot

is it right? or verse vasa?

**Comment by 130s** [comment]
@k-okada this comment looks like supposed to be added somewhere else?

```
so users will launch

jsk_pcl_ros/launch/openni_local.launch in the robot (the machine connected to the device)

and

jsk_pcl_ros/launch/openni_remote.launch in the machine that is remote from the real robot

is it right? or verse vasa?
```

**Comment by 130s** [comment]
> I basically do not like to increase the number of repository, because it is hard to maintain. if you like above idea, we can create new repo.

Agreed to reduce the number of repositories if possible. And dependency system in post-rosbuild era is nice enough to eliminate redundantly depend on `stack`/`metapackage`, adding packages that only contain sample/tutorial under the same metapackage suite does not cause any problem at all I think.

**Comment by k-okada** [comment]
creating new repo is one advantage that is can be used for test code that check debianized rtmros_hironx works or not. (easily)

**Comment by 130s** [comment]
> creating new repo is one advantage that is can be used for test code that check debianized rtmros_hironx works or not. (easily)

That sounds like more assuring factor to me. I'll then create a separate repo for demo.

**Comment by 130s** [comment]
[Created a separate package](https://github.com/tork-a/hironx_tutorial/commits/master) and [released into hydro](https://github.com/ros/rosdistro/pull/4534).
