### ISSUE TITLE
create jenkins job

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#80]
In order to make sure that if the PR is really breaks downstream package or not, I created jenkins job at http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/rtmros-common-check/

It does:
- apt-get ros-hydro-hironx-ros-bridge
- catkin_make install rtmros_common from source
- (remove hrpsys-ros-bridge, rtmbuild, hrpsys-tools just in case)
- check test code in hironx-ros-bridge

**Comment by 130s** [comment]
I'm not sure what is the purpose of this issue.
The `jenkins` job linked seems to be disabled. Is this issue already addressed somewhere else?

**Comment by k-okada** [comment]
Jenkins job is disabled since we're using travis. If there are any reason if travis did not work and need jenkins server, feel free to enable that.
