### ISSUE TITLE
test code is for simulation or real robot?

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtmros_hironx#81]
currently test code is configured to work on real robot [1].
but it is strange that in test launch file[2], it seems to designed to working on simulaiton, because it uses corba port 2809, not 15005 which rea lrobot is using[3].

Currently, I'm working on simulation (https://github.com/start-jsk/rtmros_hironx/issues/80) and would like to confgure test code for simulation environment, but I think you'd like to run `make test`, to check if the robot is working at customer side. Any idea?

[1] https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/test_hironx_ik.py#L32
[2] https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/test/test-hironx.test#L11
[3] https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/hironx_ros_bridge/robot/NameServer.sh.in#L13

**Comment by 130s** [comment]
- using the same command is the greatest.
- Slight difference with arguments are acceptable IMO.

So I think I've got working copy of utilizing .launch file where you can
run tests both from Sim and real robot with the same rostest command, with
only passing different arguments.

**Comment by k-okada** [comment]
Yes, that seems good.
Currently, we have implicit rule that all test code run in travis has .test suffix.
https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/.travis.yml#L73

test-hironx.test -> for simulation
test-hironx-real.launch -> for real

seems good. Do you have time on working on this?

**Comment by 130s** [comment]
Got it. I'll also need to document the testing principle (eg. Different use cases between .launch and .test files) somewhere.

**Comment by k-okada** [comment]
I have modified test code for travis at -> https://github.com/start-jsk/rtmros_hironx/pull/86
- change test code for simulation (current version assuming it works on real robot)
- speed up test motion and relax test condition (i'm not fully sure if it is ok, but without this travis randomly fail to test  https://github.com/k-okada/rtmros_hironx/commit/c59adc93f0c04386e34be903087650f7f0c81ff7)
- even if it says "USE_DEB=false" it uses deb for openhrp3 to speed up test.

it this is ok, please merge them @130s

**Comment by k-okada** [comment]
I forget to note one thing, I think deb did not pu__init__.py to the /opt/ros/hydro/lib/python2.7/dist-packages/hrpsys_ros_bridge, this seems very critical bug but strange that no one complain on this.

https://github.com/k-okada/rtmros_hironx/commit/689edac1e73547cb631837afd0e91d59af6f9001#diff-354f30a63fb0907d4ad57269548329e3R70

**Comment by 130s** [comment]
I might have taken the intension of this ticket in a wrong way; I thought we wanted to use the same test files for simulation and real robots, but the [suggested change](https://github.com/k-okada/rtmros_hironx/commit/1f598f0972bec06d5d6feb3062b79c67ecd7da5f) looks like the opposite. 

If this is making things better I'm fine. But then I'd like to know what tests I can use with real robots.

What I've been doing so far is (not ideal though) to manually modify `.test` files in `hironx_ros_bridge` to adjust robot name and port.

**Comment by k-okada** [comment]
You're correct. we want test code that works for both simulation and real robot. But since I want to include hironx's test code in rtmros_common and hrpsys-base backward compatibility test[1][2] and it seems this issue will not completed with in a few days, I write that patch. and leave original intention of this issue open.
If you think I should change this file working on both real and simulation at this moment, please change assignee and also I should not forget about  memo on [3]. these test is not confirmed on real robot (for example test_ik_joint_angle) and speed need to be more slower for real robot (currently I speeded up for travis)

[1] https://github.com/start-jsk/rtmros_common/pull/448
[2] https://github.com/fkanehiro/hrpsys-base/pull/212
[3] https://github.com/start-jsk/rtmros_hironx/pull/60#issuecomment-37159100

**Comment by k-okada** [comment]
@130s, can we merge https://github.com/start-jsk/rtmros_hironx/pull/86? or do I have to wait for following feature? since this PR is the beginning of https://github.com/start-jsk/rtmros_common/issues/449 and I'm afraid some one merge newer code and brake my PR again....

> If this is making things better I'm fine. But then I'd like to know what tests I can use with real robots.
> 
> What I've been doing so far is (not ideal though) to manually modify .test files in hironx_ros_bridge to adjust robot name and port.

**Comment by 130s** [comment]
```
You're correct. we want test code that works for both simulation and real robot. But since I want to include hironx's test code in rtmros_common and hrpsys-base backward compatibility test[1][2] and it seems this issue will not completed with in a few days, I write that patch. and leave original intention of this issue open.
If you think I should change this file working on both real and simulation at this moment, please change assignee and also I should not forget about memo on [3]. these test is not confirmed on real robot (for example test_ik_joint_angle) and speed need to be more slower for real robot (currently I speeded up for travis)

[1] start-jsk/rtmros_common#448
[2] fkanehiro/hrpsys-base#212
[3] #60 (comment)
```

Makes sense. 
I'll merge #86 now.
