### ISSUE TITLE
Separate tutorial into operation and programming

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#88]
This tutorial "[Operating Hiro/NEXTAGE OPEN from Client Programs](http://wiki.ros.org/rtmros_nextage/Tutorials/Operating%20Hiro,%20NEXTAGE%20OPEN%20from%20Client%20Pograms)" is too large, and mixes operation and programming that makes finding what readers want harder. Split into 2 tutorials.

**Comment by k-okada** [comment]
+1

**Comment by 130s** [comment]
Done. Programming part is moved to [a new tutorial page](http://wiki.ros.org/rtmros_nextage/Tutorials/Programming).

Btw the both operation and programming parts look very complicating to me. Who wrote that? Okay it's me. I need to review and add necessary changes. They look terrible.
