### ISSUE TITLE
What for *_nosim.conf files?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#92]
Question to @k-okada 
`catkin_make`ing `hironx_ros_bridge` package yields some `*.conf` and `_nosim.conf` files in `conf` directory. What is the difference between them?

`nosim` gives an impression of "no simulation" so that ones without `nosim` might be "simulation". ~~But as long as I look at the contents of those files I feel the opposite; `nosim` files contains more adhoc file paths and seem to be simulation.~~ If so, shouldn't we use a static file path for the model file in `kawada-hironx_nosim.conf` where the path needs to be the location of the `.wrl` file on QNX (otherwise [collision visualization](https://github.com/start-jsk/rtmros_hironx/pull/89) doesn't work).

**Comment by k-okada** [comment]
nosim is simulation without dynamics, and the other one is simulation with dynamics.

so maybe we need kawada_hironx_real.conf for real robot.

**Comment by 130s** [comment]
I see.

> so maybe we need kawada_hironx_real.conf for real robot.

It's already added in my proposed change https://github.com/130s/rtmros_hironx/commit/8081dacac2dba5c06941d8d9e0117b5f52a775f5

**Comment by 130s** [comment]
So does this change sound even better?
- Change `_nosim` --> `_sim_nodynamics`
- Change the one without attribute --> `_sim_dynamics`
- Add `_realrobot`

**Comment by k-okada** [comment]
> - Add _realrobot

I think this is ok.

but

> - Change _nosim --> _sim_nodynamics
> - Change the one without attribute --> _sim_dynamics

they are autogenerated at https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/cmake/compile_robot_model.cmake#L95, so if we change the name, we'd  have to change `comile_robot_model.cmake`, and the it causes side-effects to many packages.

**Comment by 130s** [comment]
I see. So,
- I'll add document (ros wiki might be the best for now) for `nosim` etc.
- Does `_realrobot` file also need to be auto-generated? If not I'll just commit a `XX_realrobot.conf` file.

**Comment by k-okada** [comment]
> I'll add document (ros wiki might be the best for now) for nosim etc.

Yes please

> Does _realrobot file also need to be auto-generated? If not I'll just commit a XX_realrobot.conf file.

no, currently it is not auto generated and we do not have such plan at this moment

**Comment by 130s** [comment]
[Added document on wiki](http://wiki.ros.org/action/info/hrpsys_ros_bridge?action=diff&rev2=4&rev1=3) about difference of conf files.

Static files for real robots are added ([hironx_realrobot_fixedpath.conf](https://github.com/start-jsk/rtmros_hironx/commit/bb0672be3e03e5366e03fe50520e215302b8419f#diff-bc99caa4dda21aa9b0feed9836141a80) and [hironx_ros_bridge_real.launch](https://github.com/start-jsk/rtmros_hironx/commits/bb0672be3e03e5366e03fe50520e215302b8419f/hironx_ros_bridge/launch/hironx_ros_bridge_real.launch)).
