### ISSUE TITLE
Rename HIRONX.goActual?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#94]
If I understand correctly,
- HIRONX.`goInit` moves arms to certain pose (involves physical state change).
- HIRONX.`goActual` adjusts the commanded values to the actual values of the physical devices (involves NO physical state change).

So calling the 2nd method as `goActual` might be confusing (at least to me). Don't know what is common way to call these things but maybe something like `adjustActual`?

Since the method is derived from upstream `hrpsys`, changing the name there would break api. I first suggest this here instead.

**Comment by k-okada** [comment]
> `HIRONX.goActual adjusts the commanded values to the actual values of the physical devices 

so this is used to adjust hrpsys state for physical state, especially when physical (or actual) state has changed.

The names comes from https://github.com/fkanehiro/hrpsys-base/blob/master/idl/StateHolderService.idl#L14 so I don't think it's good idea to change names only for hironx.

May be change the name from `goInit` -> `goInitPose` make sence? since we alread have `goOffPose`

**Comment by 130s** [comment]
> May be change the name from goInit -> goInitPose make sence? since we alread have goOffPose

Yes, sounds reasonable.

> >    `HIRONX.goActual adjusts the commanded values to the actual values of the physical devices
> 
> so this is used to adjust hrpsys state for physical state, especially when physical (or actual) state has changed.

`go` makes me think of actual, physical movement. Maybe because of that, I can't recall `goActual` off the top of my head when I want to do calibration.

> The names comes from https://github.com/fkanehiro/hrpsys-base/blob/master/idl/StateHolderService.idl#L14 so I don't think it's good idea to change names only for hironx.

Ok, I'll close on this repo. And I'm afraid this would break api, and maybe a bit too trivial. So I don't know if it's worth opening a discussion in `hrpsys`.
